export const CREATE_WIDGET_ERROR = "CREATE_WIDGET_ERROR";
export const CREATE_WIDGET_SUCCESS = "CREATE_WIDGET_SUCCESS";

export const UPDATE_WIDGET_ERROR = "UPDATE_WIDGET_ERROR";
export const UPDATE_WIDGET_SUCCESS = "UPDATE_WIDGET_SUCCESS";

export const REMOVE_WIDGET_ERROR = "REMOVE_WIDGET_ERROR";
export const REMOVE_WIDGET_SUCCESS = "REMOVE_WIDGET_SUCCESS";

export const LOAD_WIDGETS_SUCCESS = "LOAD_WIDGETS_SUCCESS";
export const UNLOAD_WIDGETS_SUCCESS = "UNLOAD_WIDGETS_SUCCESS";
