export const SET_RESOURCE = "CREATE_RESOURCE";
export const SET_RESOURCE_ERROR = "CREATE_RESOURCE_ERROR";

export const UPDATE_RESOURCE = "UPDATE_RESOURCE";
export const UPDATE_RESOURCE_ERROR = "UPDATE_RESOURCE_ERROR";

export const DESTROY_RESOURCE = "DESTROY_RESOURCE";
export const DESTROY_RESOURCE_ERROR = "DESTROY_RESOURCE_ERROR";